name: GitHub Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy to gh-pages
        run: |
          git config --global user.name gaisdav
          git config --global user.email gais.davletkildin@gmail.com
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
          env:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
