name: GitHub Actions for builds test
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build production
        run: npm run build
      - name: Build for local serve
        run: npm run serve-build
      - name: Build for github pages
        run: npm run gh-pages-build
