name: GitHub Actions for builds test
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      WIREIT_PARALLEL: 3
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v1
      - name: Install dependencies
        run: npm ci
      - name: Test build production
        run: |
          export WIREIT_PARALLEL=3
          npm run test-build
